database:
  path: data/feedback.db
models:
  embedder: sentence-transformers/all-MiniLM-L6-v2
  recommender: IlyaGusev/saiga_mistral_7b_lora
  temperature: 0.8
rag:
  top_k: 5
  similarity_threshold: 0.8
processing:
  include_neutral: false
  use_fallback_data: true
  product_description: "SaaS tool for managing customer feedback" # company/product description
  use_relevance_filter: true
  relevance_threshold: 0.5
  remove_stopwords: false
  stopwords_language: russian
  default_brand: ППР